### ISSUE TITLE
Not working on raspi

### ISSUE THREAD

**Issue by 9M2PJU** [iz3mez/dxspider-basic-web#1]
![image](https://github.com/iz3mez/dxspider-basic-web/assets/991353/2d067691-605e-4907-8ce3-fed06edc7451)

**Comment by iz3mez** [comment]
if it does not display it means that the php script cannot access the database. Check that the database is active, the tables with spot data and database username, password are correct. Raspberry, Server or other makes no difference. You must have the PHP libraries installed to access MySQL or MariaDB databases.

**Comment by 9M2PJU** [comment]
<img width="393" alt="image" src="https://github.com/iz3mez/dxspider-basic-web/assets/991353/c9dfee58-0599-4365-bd1c-c5d07731900d">


i think i set it right, but when i read dxcluster database there is nothing there
hmmm..
